# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generateCompositions <- function(n) {
    .Call('multicool_generateCompositions', PACKAGE = 'multicool', n)
}

Stirling2C <- function(n, k) {
    .Call('multicool_Stirling2C', PACKAGE = 'multicool', n, k)
}

BellC <- function(n) {
    .Call('multicool_BellC', PACKAGE = 'multicool', n)
}

createMCObj <- function(iSet) {
    .Call('multicool_createMCObj', PACKAGE = 'multicool', iSet)
}

allPermC <- function(id) {
    .Call('multicool_allPermC', PACKAGE = 'multicool', id)
}

nextPermC <- function(id) {
    .Call('multicool_nextPermC', PACKAGE = 'multicool', id)
}

multinomCoeff <- function(x) {
    .Call('multicool_multinomCoeff', PACKAGE = 'multicool', x)
}

